deploymentMode: Monolithic

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage:
    type: filesystem
  limits_config:
    retention_period: 72h
  compactor:
    retention_enabled: true
    delete_request_store: filesystem
  rulerConfig:
    enable_api: true
    alertmanager_url: http://monitoring-kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
    evaluation_interval: 10s
    storage:
      type: local
      local:
        directory: /etc/loki/rules

ruler:
  enabled: false

singleBinary:
  replicas: 1
  extraVolumes:
    - name: chatbox-pod-event-rules
      configMap:
        name: chatbox-pod-event-rules
  extraVolumeMounts:
    - name: chatbox-pod-event-rules
      mountPath: /etc/loki/rules/fake
      readOnly: true
  persistence:
    enabled: true
    storageClass: local-path
    size: 5Gi
  resources:
    requests:
      cpu: 50m
      memory: 192Mi
    limits:
      cpu: 500m
      memory: 384Mi

gateway:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 100m
      memory: 64Mi

lokiCanary:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

test:
  enabled: false
