apiVersion: apps/v1
kind: Deployment
metadata: {name: chatbox-backend, namespace: chatbox1}
spec:
  replicas: 1
  selector:
    matchLabels: {app: chatbox-backend}
  template:
    metadata:
      labels: {app: chatbox-backend}
    spec:
      containers:
        - name: backend
          image: ghcr.io/nguyen-trung-hieu1/chatbox-backend:sha-e7e4f23d06dcae229244c9f7259f4659b0bef065
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef: {name: chatbox-backend-config}
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket: {port: 8080}
            initialDelaySeconds: 3
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata: {name: chatbox-backend, namespace: chatbox1}
spec:
  selector: {app: chatbox-backend}
  ports:
    - {port: 8080, targetPort: 8080}
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: chatbox-frontend, namespace: chatbox1}
spec:
  replicas: 1
  selector:
    matchLabels: {app: chatbox-frontend}
  template:
    metadata:
      labels: {app: chatbox-frontend}
    spec:
      containers:
        - name: frontend
          image: ghcr.io/nguyen-trung-hieu1/chatbox-frontend:sha-e7e4f23d06dcae229244c9f7259f4659b0bef065
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: {path: /, port: 80}
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata: {name: chatbox-frontend, namespace: chatbox1}
spec:
  selector: {app: chatbox-frontend}
  ports:
    - {port: 80, targetPort: 80}
